server:
  port: 8089

spring:
  datasource:
    url: jdbc:h2:./db/demo;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  mvc:
    static-path-pattern: /static/**

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info

    #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

  file:
    name: logs/spring.log